見出しコンポーネントを作成
conea0/course-library pull request #35
Opened 2023-11-07 03:53 UTC by SHO800

左側のバーの色は#424242で固定してます
CssModules使いました
src/componentsの下にheadingというフォルダを作成しました

2023-11-08 12:13 UTC, syuya2036 approved these changes
lgtm

2023-11-08 12:35 UTC, h-koichiro requested changes
お願いします:)

2023-11-08 12:35 UTC, h-koichiro commented on src/components/heading/heading.tsx
> +export default Heading;
名前付きexportで良いと思います

2023-11-08 12:35 UTC, h-koichiro commented on src/components/heading/heading.module.css
> +    /*background: red;*/
不要なコメントです : )

2023-11-08 12:35 UTC, h-koichiro commented on src/components/heading/heading.module.css
> +.wrapper::after {
blockの間に改行 : )

2023-11-08 12:35 UTC, h-koichiro commented on src/components/heading/heading.module.css
> +}
最後の行の改行 :)

2023-11-09 05:46 UTC, SHO800 commented on src/components/heading/heading.module.css
> +    /*background: red;*/
okay

2023-11-09 05:46 UTC, SHO800 commented on src/components/heading/heading.module.css
> +.wrapper::after {
okay

2023-11-09 05:46 UTC, SHO800 commented on src/components/heading/heading.module.css
> +}
okay

2023-11-09 05:48 UTC, SHO800 commented on src/components/heading/heading.tsx
> +export default Heading;
okay

2023-11-09 07:17 UTC, h-koichiro commented
左側のバーの色は#424242で固定してます
＞＞＞メンバーとの確認が取れ次第、#2E3838に変更お願いします

#2E3838について
サイトのメインカラーです。もしメンバーで配色を吟味する必要があれば保留でお願いします。
@syuya2036 配色についての言及です。ご確認お願い致します。

2023-11-09 14:32 UTC, syuya2036 commented
gitognoreに指定する前にpushしたやつは無視されないので、一旦移動してからコミット→元に戻す、とした方がいいかもしれません
@SHO800

2023-11-09 22:01 UTC, SHO800 commented
> 一旦移動してからコミット→元に戻す、とした方がいいかもしれません
すみません、これはどういうことでしょうか?@syuya2036

2023-11-10 04:44 UTC, h-koichiro commented
lgtm

2023-11-10 12:19 UTC, syuya2036 approved these changes
lgtm

2023-11-10 12:31 UTC, h-koichiro approved these changes
lgtm :)_

2023-11-12 06:23 UTC, merged