サイドバーのコンポーネントを作成
conea0/course-library pull request #38
Opened 2023-11-09 07:18 UTC by h-koichiro

asideの中に「ロゴ」と「サイドバー」があるイメージです。
publicの中の/imagesにiconなどを追加しました。

2023-11-09 07:19 UTC, h-koichiro commented
@syuya2036

2023-11-09 11:42 UTC, h-koichiro commented
追記：globals.cssもいじって変数に配色などを定義しました
@syuya2036

2023-11-09 14:39 UTC, syuya2036 requested changes

2023-11-09 14:39 UTC, syuya2036 commented on src/components/aside/sidebar/sidebar.tsx
> +export const Sidebar = () => {
propsでデータを渡すようにして、mapで表示させるようにできますか？

2023-11-10 06:57 UTC, h-koichiro commented on src/components/aside/sidebar/sidebar.tsx
> +export const Sidebar = () => {
変更しました。レビューお願いします
@syuya2036 
: )

2023-11-10 12:32 UTC, syuya2036 approved these changes
lgtm

2023-11-10 12:32 UTC, merged