問題文を表示するカード＆問題文とテストケースの型定義をする
conea0/course-library pull request #45
Opened 2023-11-12 08:27 UTC by h-koichiro

型定義について、getProblemの引数をpart,unit,idにしました。

問題文を表示するカードでは、ホバー時の視差効果としてborder-topとborder-bottomを追加しました。

figmaの構想とか微妙に違うのでそのへんも吟味していただけると幸いです。

2023-11-15 02:00 UTC, h-koichiro commented
@syuya2036 
お待たせしました！
修正も含め完了しました！

2023-11-15 14:00 UTC, syuya2036 requested changes
uiは最高に綺麗でした✨

2023-11-15 14:00 UTC, syuya2036 commented on src/app/page.tsx
> +      <ProblemBox part={0} unit={0} id={0} />
part={0} unit={0} id={0}を一つにまとめて渡そう

2023-11-19 01:39 UTC, h-koichiro commented
ごめんなさい！仕事終わっていたと思ったら、ルーティング関連の修正のことすっかり忘れていました：）

URLの取得とクエリの取得方法についてですが、もっといい書き方があるかもしれないです…

2023-11-19 08:07 UTC, syuya2036 approved these changes

2023-11-19 09:40 UTC, merged